### ISSUE TITLE
多次开关闭播放界面，当视频在播放时，按Home键进入后台，程序再从后台进入前台，程序崩溃

### ISSUE THREAD

**Issue by SkyOldLee** [MoboPlayer/TestMyMoboPlayer#21]
测试了新版MoboPlayer，按标题操作四五次，程序崩溃。崩溃时，截图如下：
![qq 20150105145211](https://cloud.githubusercontent.com/assets/8748528/5610131/0913f202-94ec-11e4-9b88-ad8f64527e5b.jpg)

**Comment by sunjun** [comment]
check this fix
a5d306147c0cc8a7a1a42c6c77a8d77d0dd05700

**Comment by SkyOldLee** [comment]
问题解决，谢谢了。
