### ISSUE TITLE
新版MoboPlayer播放不了网络视频，“打开文件失败”的警告框弹出多次

### ISSUE THREAD

**Issue by SkyOldLee** [MoboPlayer/TestMyMoboPlayer#22]
刚才测试了下，新版MoboPlayer播放不了网络视频（将parameters[MoboParameterRTMPLive]设置为@(NO)或者@(YES)，都播不了）。本地视频是可以播放的（将parameters[MoboParameterRTMPLive]设置为@(NO)或者@(YES)，都播的了）。
    当播不了网络视频时，MoboPlayerErrorHandle协议的handleError会执行多次，导致“打开文件失败”的警告框弹出多次。（当第n次播放网络视频时，警告框会弹出n次）

**Comment by sunjun-clov4r** [comment]
d01c51d

**Comment by SkyOldLee** [comment]
刚才测试了下，问题解决，谢谢了！
