### ISSUE TITLE
TestMyMoboPlayer的self.topPanel和self.bottomPanel的隐藏与显示问题

### ISSUE THREAD

**Issue by SkyOldLee** [MoboPlayer/TestMyMoboPlayer#23]
在12月31号的版本中，将self.view替换成self.moboPlayer.moboDisplayView，如下图：
![qq 20150112143506](https://cloud.githubusercontent.com/assets/8748528/5699689/a232f2d6-9a68-11e4-9543-42bdae0f2bd4.jpg)
    当播放视频时，点击播放界面toggleControlsVisible的函数不会执行，就不能实现self.topPanel和self.bottomPanel的隐藏与显示了。
    孙工，这个问题怎么解决？谢谢了

**Comment by sunjun** [comment]
5721d59 
check this fix

**Comment by SkyOldLee** [comment]
问题解决。
如上图，将self.moboPlayer.moboDisplayView替换成self.view。
