### ISSUE TITLE
当修改scalingMode时，MoboPlayerScalingModeNone与MoboPlayerScalingModeAspectFit表现的缩放形式一样

### ISSUE THREAD

**Issue by SkyOldLee** [MoboPlayer/TestMyMoboPlayer#24]
在新版的MoboPlayer的MyVideoViewController.m中的changeScalingMode函数修改如下：
![qq 20150112145345](https://cloud.githubusercontent.com/assets/8748528/5699776/02f3742c-9a6b-11e4-829c-77d48ddfb66e.jpg)
当双击视频播放界面时，MoboPlayerScalingModeNone与MoboPlayerScalingModeAspectFit表现的缩放形式一样。
    孙工，MoboPlayerScalingModeNone与MoboPlayerScalingModeAspectFit是否需要删除一个，还是怎么办？谢谢了！

**Comment by sunjun** [comment]
不需要删除 这两个是一个
MoboPlayerScalingModeNone代表默认 
就是MoboPlayerScalingModeAspectFit

**Comment by SkyOldLee** [comment]
好的，那我在changeScalingMode函数中，随便删除modes数组中的MoboPlayerScalingModeNone或者MoboPlayerScalingModeAspectFit就可以了。
