### ISSUE TITLE
有些视频不能靠双击播放界面修改scalingMode

### ISSUE THREAD

**Issue by SkyOldLee** [MoboPlayer/TestMyMoboPlayer#25]
在12月31号的版本中，将MyVideoViewController.m中的self.view替换成self.moboPlayer.moboDisplayView，如下图：
![qq 20150112143506](https://cloud.githubusercontent.com/assets/8748528/5699928/7f4e4698-9a6e-11e4-9db9-203fbf2948ce.jpg)

    当双击播放界面，有些视频（test.flv、VE.flv）不能靠双击播放界面修改scalingMode，即这些视频双击播放界面不会执行changeScalingMode函数。这些视频，播放时，控制台都有如下输出：
![qq 20150112151749](https://cloud.githubusercontent.com/assets/8748528/5699978/7168c20a-9a6f-11e4-868e-b30c49f732f0.jpg)
    孙工，这个问题怎么解决？谢谢了！

**Comment by sunjun** [comment]
5721d59 
check this fix

**Comment by SkyOldLee** [comment]
问题解决。
如第一幅图，将self.moboPlayer.moboDisplayView替换成self.view。
